import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import CalendarPage from "@/components/pages/calendar/CalendarPage";
import styles from "@/styles/Home.module.css";

export default function Calendar() {
  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CalendarPage/>
      </div>
    </>
  );
}

Calendar.getLayout = (pageProps) => (
  <MainLayout>
    <Calendar {...pageProps} />
  </MainLayout>
);
