import Head from "next/head";
import CustomersDetail from "@/components/pages/customers/CustomersDetail"
import BarChart from '@/components/pages/customers/CustomerBarChart'
import Cart from '@/components/pages/customers/CustomersRightSide'
import Cart2 from '@/components/pages/customers/CustomersLeftSideFirst'
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/CustomersDetail.module.css";

export default function CustomerDetail() {
  return (
    <>
      <Head>
        <title>Cutomers Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles['dee']}>
        <CustomersDetail/>
        <Cart/>
        </div>
        <div className={styles['dfss']}>
        <Cart2/>
        <BarChart/>
        </div>
      </div>
    </>
  );
}

CustomerDetail.getLayout = (pageProps) => (
  <MainLayout>
    <CustomerDetail {...pageProps} />
  </MainLayout>
);
