import Head from "next/head";
import FoodDetail from "@/components/pages/food-detail/FoodDetail";
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/Home.module.css";

export default function FoodsDetail() {
  return (
    <>
      <Head>
        <title>FoodDetail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <FoodDetail/>
      </div>
    </>
  );
}

FoodsDetail.getLayout = (pageProps) => (
  <MainLayout>
    <FoodsDetail {...pageProps} />
  </MainLayout>
);
